spring.application.name=ss_day1_ex2

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

cors.allowed.origin=*
cors.allowed.method=*
cors.allowed.header=*