spring.application.name=ss_day4_ex2

server.port=9090

spring.security.oauth2.client.registration.client.client-id=client
spring.security.oauth2.client.registration.client.client-secret=secret
spring.security.oauth2.client.registration.client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.client.scope=openid
spring.security.oauth2.client.provider.client.token-uri=http://localhost:8080/oauth2/token

spring.security.oauth2.client.registration.client2.client-id=client
spring.security.oauth2.client.registration.client2.client-secret=secret
spring.security.oauth2.client.registration.client2.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.client2.scope=openid
spring.security.oauth2.client.provider.client2.token-uri=http://localhost:8080/oauth2/token